version: "3"

services:
  app:
    container_name: JustKanbanDev
    image: justkanban:dev
    build:
      context: ../
      dockerfile: ./Dockerfile
    ports:
      - "${APP_HOST_PORT}:${APP_HOST_PORT}"
    tty: true
    networks:
      - justkanban-dev
    depends_on:
      - mongodb-docker

  mongodb-docker:
    image: mongo:latest
    container_name: DockerMongoDB
    volumes:
      - data-volume:/data/db
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    networks:
      - justkanban-dev

networks:
  justkanban-dev:
    driver: bridge

volumes:
  data-volume:
